---
kerberos_realm: EXAMPLE.COM
kerberos_domain: example.com
kerberos_kdc_hosts: []
kerberos_deploy_krb5_conf: true
kerberos_run_kinit: true
kerberos_krb5_conf_path: /etc/krb5.conf
kerberos_dns_lookup_kdc: true
