---
controller_hosts:
  - name: localhost
    inventory: "{{ playground_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-01
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-02
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-03
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-04
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-05
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-06
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-07
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-08
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-09
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local

  - name: fake-host-10
    inventory: "{{ playground_fake_hosts_inventory_name }}"
    variables:
      ansible_connection: local
